version: '3.9'

services:
    react-app:
        build:
            context: ./react-app
            dockerfile: Dockerfile
        ports:
            - "3000:443"
        networks:
            - firebase_network
        depends_on:
            - firebase-emulator

    firebase-emulator:
        build:
            context: ./firebase
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
            - "4500:4500"
        networks:
            - firebase_network
        volumes:
            - firebase-data:/firebase-data

networks:
    firebase_network:
        driver: bridge

volumes:
    firebase-data:
